<?php
return array(
	'i18n_alreadyactivated'=>'Your account is already activated. Contact us if you have problems loggin in.',
	'i18n_registration'=>'Registration',
	'i18n_register_oops'=>'Something went wrong, try again.',
	'i18n_error'=>'Error',
	'i18n_reg_update_success'=>'Your account has been saved. It is now activated and you can now <a href="/login">log in</a>.',	
	'i18n_confirmation_mail_subject'=>'Your account on ',
	'i18n_confirmation_mail_message'=>'<p>Hi,</p><p>Your account on our website is almost created! </p><p>Click on this link or copy and paste it in your browser to complete your registration: ',
	'i18n_username'=>'Username',
	'i18n_password'=>'Password',
	'i18n_password_conf'=>'Confirm password',
	'i18n_login'=>'Login',
	'i18n_logout'=>'Logout',
	'i18n_msg'=>'Message',
	'i18n_register'=>'Register',
	'i18n_lostpassword'=>'Lost password',	
	'i18n_lostpassword_msg'=>'Enter your new password and click on <em>Change Password</em>.',
	'i18n_changepassword'=>'Change password',	
	'i18n_user_wrong_confirm'=>'Password and confirmation do not correspond.',
	'i18n_password_too_short'=>'The password needs to be at least 8 characters long.',
	'i18n_new_password_request_header'=>'New password requested',
	'i18n_new_password_request'=>"<p>If the emailadress exists in our database, we have sent a message with further instructions to it.</p> ",
	'i18n_settings'=>'Settings',
	'i18n_create_user'=>'Create User',
	'i18n_update_user'=>'Update User',
	'i18n_errorpage_header'=>'There has been a problem',
	'i18n_401'=>'You have no access to this page (401).',
	'i18n_403'=>'You have no access to this page (403).',
	'i18n_404'=>'400 - Page not found',
	'i18n_500'=>'It\'s not you, it\'s us. Something went terribly wrong and we should fix that.',
	'i18n_other_error'=>'An unexpected error has arisen. If this keeps happening, we would appreciate a quick message about it.',
	'i18n_email'=>'Email',	
	'i18n_wrong_login'=>'The combination of username and password is wrong. Try again.',
	'i18n_not_activated'=>'Your account has not yet been activated. If you haven\'t received an activation mail you can try to send it again: <a href="/sendactivationmail">click here to send the activation mail again</a>.<br>Haven\'t received anything from us? Check your spam folder.',
	'i18n_send_registration_mail_again'=>'If you haven\'t received a confirmation link in your inbox yyou can try to send it again. Give your email here.<br>No mail received? Check your spam folder.',
	'i18n_send_registration_mail_again_ok'=>'The mail has been sent.',
	'i18n_user_success'=>'The user has been created',
	'i18n_account_update'=>'Update account',
	'i18n_user_error'=>'There was an error',
	'i18n_reg_conf_success'=>'Your email has been confirmed. Your account is now activated and you can now <a href="/login">log in</a>.',
	'i18n_reg_conf_failed'=>'There was a problem activating your account. Contact us if you are unable to create an account.',

	'i18n_username_taken'=>'This username is not available, Please choose a different username.',
	'i18n_email_taken'=>'This email is already taken. Login or choose another email to create an account.',
	
	'i18n_conf_mail_sent'=>'<p>Thank you for registering on our website. </p><p>We have sent you a mail with further instructions to activate your account.</p><p>If you haven\'t received a mail from us, please check your spam folder.</p>', 
	'i18n_registration_confirmation_failed'=>'Something went wrong activating your account.',
	'i18n_agree_conditions'=>' I have read the conditions and agree with them',
	'i18n_submit'=>'Submit',
	
	'i18n_reset_pw'=>'Fill out your email and click submit in order to reset your password. Follow the instructions we send to you by mail.',
	'i18n_reset_pw_submit'=>'Reset Password',
	'i18n_password_changed'=>'Password changed succesfully',
	'i18n_password_changed_error'=>'There was a problem changing your password',
	'i18n_resend_activation_mail'=>'Resend activation mail',
	'i18n_users'=>'Users'
);
